import ModuleTablePage from '../components/ModuleTablePage';
import DetailModal, { DetailGrid } from '../components/DetailModal';
import { products, productGroups } from '../data/mockData';

const config={eyebrow:'GESTIÓN · INVENTARIOS',title:'Módulo de inventarios',description:'Consulte productos por nombre, grupo y cantidad disponible. El resultado presenta existencias y permite acceder al detalle del producto.',tableTitle:'Productos encontrados',sortLabel:'nombre ascendente',initialFilters:{name:'',group:'',minHoldings:'',maxHoldings:''}};
const columns=[{key:'name',label:'Producto'},{key:'group',label:'Grupo'},{key:'holdings',label:'Cantidad en inventario'}];
const filterData=(data,f)=>data.filter(r=>r.name.toLowerCase().includes(f.name.trim().toLowerCase())&&(!f.group||r.group===f.group)&&(f.minHoldings===''||r.holdings>=Number(f.minHoldings))&&(f.maxHoldings===''||r.holdings<=Number(f.maxHoldings)));

function InventoryPage(){return <ModuleTablePage config={config} data={products} filterData={filterData} tableColumns={columns}
 renderFilters={({filters,updateFilter})=><><label className="field"><span>Nombre del producto</span><input value={filters.name} onChange={e=>updateFilter('name',e.target.value)} placeholder="Ej. mug"/></label><label className="field"><span>Grupo</span><select value={filters.group} onChange={e=>updateFilter('group',e.target.value)}><option value="">Todos</option>{productGroups.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Cantidad mínima</span><input type="number" min="0" value={filters.minHoldings} onChange={e=>updateFilter('minHoldings',e.target.value)} placeholder="0"/></label><label className="field"><span>Cantidad máxima</span><input type="number" min="0" value={filters.maxHoldings} onChange={e=>updateFilter('maxHoldings',e.target.value)} placeholder="Sin límite"/></label></>}
 renderDetail={({selected,setSelected,placeholderAction})=><DetailModal open={!!selected} title={selected?.name} subtitle={selected?.group} onClose={()=>setSelected(null)} footer={<><button className="button secondary" onClick={placeholderAction}>Editar</button><button className="button danger" onClick={placeholderAction}>Eliminar</button></>}>{selected&&<DetailGrid items={[{label:'Nombre del producto',value:selected.name},{label:'Proveedor',value:selected.supplier},{label:'Color',value:selected.color},{label:'Unidad de empaquetamiento',value:selected.unitPackage},{label:'Empaquetamiento exterior',value:selected.outerPackage},{label:'Cantidad de empaquetamiento',value:selected.quantity},{label:'Marca',value:selected.brand},{label:'Talla / tamaño',value:selected.size},{label:'Impuesto',value:`${selected.tax}%`},{label:'Precio unitario',value:`$${selected.unitPrice}`},{label:'Precio de venta recomendado',value:`$${selected.retailPrice}`},{label:'Peso',value:selected.weight},{label:'Cantidad disponible',value:selected.holdings},{label:'Ubicación',value:selected.location},{label:'Palabras clave',value:selected.searchDetails,wide:true}]}/>}</DetailModal>}
 />}
export default InventoryPage;
