import ModuleTablePage from '../components/ModuleTablePage';
import DetailModal, { DetailGrid } from '../components/DetailModal';
import DataTable from '../components/DataTable';
import { sales, deliveryMethods } from '../data/mockData';

const money=(v)=>new Intl.NumberFormat('es-CR',{style:'currency',currency:'USD'}).format(v);
const config={eyebrow:'GESTIÓN · VENTAS',title:'Módulo de ventas',description:'Consulte facturas por cliente, rango de fechas, método de entrega y rango de monto. Seleccione una venta para ver su encabezado y detalle.',tableTitle:'Ventas encontradas',sortLabel:'nombre del cliente ascendente',initialFilters:{client:'',dateFrom:'',dateTo:'',deliveryMethod:'',minAmount:'',maxAmount:''}};
const columns=[{key:'invoiceNumber',label:'Factura'},{key:'date',label:'Fecha'},{key:'client',label:'Cliente'},{key:'deliveryMethod',label:'Método de entrega'},{key:'amount',label:'Monto',render:(v)=>money(v)}];
const filterData=(data,f)=>data.filter(r=>r.client.toLowerCase().includes(f.client.trim().toLowerCase())&&(!f.dateFrom||r.date>=f.dateFrom)&&(!f.dateTo||r.date<=f.dateTo)&&(!f.deliveryMethod||r.deliveryMethod===f.deliveryMethod)&&(f.minAmount===''||r.amount>=Number(f.minAmount))&&(f.maxAmount===''||r.amount<=Number(f.maxAmount)));

function SalesPage(){return <ModuleTablePage config={config} data={sales} filterData={filterData} tableColumns={columns}
 renderFilters={({filters,updateFilter})=><><label className="field"><span>Nombre del cliente</span><input value={filters.client} onChange={e=>updateFilter('client',e.target.value)} placeholder="Ej. Tailspin"/></label><label className="field"><span>Fecha desde</span><input type="date" value={filters.dateFrom} onChange={e=>updateFilter('dateFrom',e.target.value)}/></label><label className="field"><span>Fecha hasta</span><input type="date" value={filters.dateTo} onChange={e=>updateFilter('dateTo',e.target.value)}/></label><label className="field"><span>Método de entrega</span><select value={filters.deliveryMethod} onChange={e=>updateFilter('deliveryMethod',e.target.value)}><option value="">Todos</option>{deliveryMethods.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Monto mínimo</span><input type="number" min="0" value={filters.minAmount} onChange={e=>updateFilter('minAmount',e.target.value)} placeholder="0"/></label><label className="field"><span>Monto máximo</span><input type="number" min="0" value={filters.maxAmount} onChange={e=>updateFilter('maxAmount',e.target.value)} placeholder="Sin límite"/></label></>}
 renderDetail={({selected,setSelected,placeholderAction})=><DetailModal open={!!selected} title={selected?.invoiceNumber} subtitle={selected?`${selected.client} · ${selected.date}`:''} onClose={()=>setSelected(null)} footer={<><button className="button secondary" onClick={placeholderAction}>Editar</button><button className="button danger" onClick={placeholderAction}>Eliminar</button></>}>{selected&&<><h3 className="modal-section-title">Encabezado de la factura</h3><DetailGrid items={[{label:'Número de factura',value:selected.invoiceNumber},{label:'Cliente',value:selected.client},{label:'Método de entrega',value:selected.deliveryMethod},{label:'Orden de compra',value:selected.orderNumber},{label:'Persona de contacto',value:selected.contact},{label:'Vendedor',value:selected.salesperson},{label:'Fecha de factura',value:selected.date},{label:'Monto',value:money(selected.amount)},{label:'Instrucciones de entrega',value:selected.instructions,wide:true}]}/><h3 className="modal-section-title">Detalle de la factura</h3><DataTable rows={selected.lines} getRowKey={(r)=>`${r.product}-${r.quantity}`} columns={[{key:'product',label:'Producto'},{key:'quantity',label:'Cantidad'},{key:'unitPrice',label:'Precio unitario',render:v=>money(v)},{key:'taxRate',label:'Impuesto',render:v=>`${v}%`},{key:'taxAmount',label:'Monto impuesto',render:v=>money(v)},{key:'lineTotal',label:'Total línea',render:v=>money(v)}]} /></>}</DetailModal>}
 />}
export default SalesPage;
