import ModuleTablePage from '../components/ModuleTablePage';
import DetailModal, { DetailGrid } from '../components/DetailModal';
import { suppliers, supplierCategories, deliveryMethods } from '../data/mockData';

const config = { eyebrow:'GESTIÓN · PROVEEDORES', title:'Módulo de proveedores', description:'Consulte proveedores por nombre, categoría y método de entrega. Los filtros pueden combinarse y restaurarse en cualquier momento.', tableTitle:'Proveedores encontrados', sortLabel:'nombre ascendente', initialFilters:{name:'',category:'',deliveryMethod:''} };
const columns = [{key:'name',label:'Nombre del proveedor'},{key:'category',label:'Categoría'},{key:'deliveryMethod',label:'Método de entrega'}];
const filterData=(data,f)=>data.filter(r=>r.name.toLowerCase().includes(f.name.trim().toLowerCase())&&(!f.category||r.category===f.category)&&(!f.deliveryMethod||r.deliveryMethod===f.deliveryMethod));

function SuppliersPage(){return <ModuleTablePage config={config} data={suppliers} filterData={filterData} tableColumns={columns}
 renderFilters={({filters,updateFilter})=><><label className="field"><span>Nombre del proveedor</span><input value={filters.name} onChange={e=>updateFilter('name',e.target.value)} placeholder="Ej. Contoso"/></label><label className="field"><span>Categoría</span><select value={filters.category} onChange={e=>updateFilter('category',e.target.value)}><option value="">Todas</option>{supplierCategories.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Método de entrega</span><select value={filters.deliveryMethod} onChange={e=>updateFilter('deliveryMethod',e.target.value)}><option value="">Todos</option>{deliveryMethods.map(x=><option key={x}>{x}</option>)}</select></label></>}
 renderDetail={({selected,setSelected,placeholderAction})=><DetailModal open={!!selected} title={selected?.name} subtitle={selected?.reference} onClose={()=>setSelected(null)} footer={<><button className="button secondary" onClick={placeholderAction}>Editar</button><button className="button danger" onClick={placeholderAction}>Eliminar</button></>}>{selected&&<><DetailGrid items={[{label:'Código del proveedor',value:selected.reference},{label:'Nombre',value:selected.name},{label:'Categoría',value:selected.category},{label:'Contacto primario',value:selected.primaryContact},{label:'Contacto alternativo',value:selected.alternateContact},{label:'Método de entrega',value:selected.deliveryMethod},{label:'Ciudad',value:selected.city},{label:'Código postal',value:selected.postalCode},{label:'Teléfono',value:selected.phone},{label:'Fax',value:selected.fax},{label:'Sitio web',value:selected.website,link:selected.website},{label:'Nombre del banco',value:selected.bankName},{label:'Cuenta corriente',value:selected.bankAccount},{label:'Días de gracia',value:selected.paymentDays},{label:'Dirección de entrega',value:selected.deliveryAddress,wide:true},{label:'Dirección postal',value:selected.postalAddress,wide:true}]}/><div className="map-placeholder"><strong>Localización de entrega</strong><span>{selected.coordinates}</span><div className="map-grid">Mapa preparado para integrar proveedor cartográfico</div></div></>}</DetailModal>}
 />}
export default SuppliersPage;
